# Generated by Django 4.1.3 on 2023-05-14 23:01

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Predpisania",
            fields=[
                ("Zakazchik", models.CharField(max_length=63)),
                ("Podryadchik", models.CharField(max_length=63)),
                ("Id", models.CharField(max_length=31)),
                ("Narushenie", models.CharField(max_length=255)),
                ("NTD", models.CharField(max_length=255)),
                ("predp_date", models.DateField()),
                ("exp_date", models.DateField()),
                ("SK_FIO", models.CharField(max_length=63))
            ],
        ),
    ]
